### ISSUE TITLE
$ZEOF does not work properly with /proc files

### ISSUE THREAD

**Issue by shabiel** [YottaDB/YottaDB#120]
# Final Release Note

# Description

Reading /proc files on Linux seems to always return $ZEOF as true.

Test Program (LINES should have multiple entries, not a single entry):
```
TEST2 ; $ZEOF /proc bug;2018-01-02  8:47 AM
 S ^SAM=1
 K ^SAM
 N CNT S CNT=1
 N LINES
 N F S F="/proc/"_$J_"/io"
 O F:(READONLY:REWIND):0 E  Q
 U F
 N X F  R X:0  S LINES(CNT)=X,CNT=CNT+1  Q:$ZEOF
 U 0 C F
 ZWRITE LINES
 ;
 w !!
 ;
 zsystem "cat /proc/"_$J_"/io > /tmp/booio"
 N CNT S CNT=1
 N LINES
 N F S F="/tmp/booio"
 O F:(READONLY:REWIND):0 E  Q
 U F
 N X F  R X:0  S LINES(CNT)=X,CNT=CNT+1  Q:$ZEOF
 U 0 C F
 ZWRITE LINES
 QUIT
```

# Draft Release Note

$ZEOF works correctly for files in the /proc file system. Previously, $ZEOF used to incorrectly return 1 after reading one line of such files even though the file had many more lines.

**Comment by shabiel** [comment]
```
FOIA201712>w $ZV
GT.M V6.3-002 Linux x86_64
FOIA201712>w $ZYRE
YottaDB r1.10 Linux x86_64
FOIA201712>zsy "uname -a"
Linux ibis 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nars1** [comment]
Sam, thanks for the report. It is indeed a longstanding issue with handling files in the /proc file system. An fstat() or stat() of such files returns a 0 value for the file size even though the file contains valid data and this special case needs to be handled. This will be fixed soon.

Below is from the man pages of stat().

```For most files under the /proc directory, stat() does not return the file size in the st_size field; instead the field is returned with the value 0.```
