### ISSUE TITLE
Locks have subscript (each) limit of 255 bytes

### ISSUE THREAD

**Issue by estess** [YottaDB/YottaDB#127]
# Final Release Note

# Description
The op_lkname() routine that creates the private lock block for each lock specified has a specific check in it that the subscripts do not exceed 255 bytes. This was probably missed out when the max DB key size was changed from 255 to 1019. The var name along with all of its subscripts must fit into key with a max size of 1019. 

# Draft Release Note
Locks allow subscripts to be up to a size where the subscript can fit in a 1019 byte key given how much of the key is already used. Previously the length was hardcoded at 255 bytes but took no account of how much of the key was actually available.

**Comment by ksbhaskar** [comment]
255 bytes is the limit on lock resource names in the upstream code. This is not an issue and is not a limitation that anyone needs increased.
