### ISSUE TITLE
`ydb_dist` seems to overriden based on location of mumps executable

### ISSUE THREAD

**Issue by ztmr** [YottaDB/YottaDB#198]
When you set `ydb_dist` or `gtm_dist` to it's `utf8` subdirectory and have a standard install (most of the `utf8` files are symlinked to the main non-utf8 directory), these variables are forcibly changed to the directory where the binary is physically located (where the symlink is pointing to).

An example tells you everything:
```
$ docker run -ti --rm -e gtm_dist=/opt/yottadb/r1.20-x86_64/utf8 -e ydb_dist=/opt/yottadb/r1.20-x86_64/utf8 --entrypoint /bin/bash yottadb/yottadb:r1.20
root@060795d9bf65:/data# 
root@060795d9bf65:/data# 
root@060795d9bf65:/data# echo $ydb_dist
/opt/yottadb/r1.20-x86_64/utf8
root@060795d9bf65:/data# 
root@060795d9bf65:/data# 
root@060795d9bf65:/data# $ydb_dist/mumps -di

YDB>w $ztrnlnm("ydb_dist")
/opt/yottadb/r1.20-x86_64
YDB>h
root@060795d9bf65:/data# 
root@060795d9bf65:/data# 
root@060795d9bf65:/data# cd $ydb_dist/

root@060795d9bf65:/opt/yottadb/r1.20-x86_64/utf8# unlink mumps 
root@060795d9bf65:/opt/yottadb/r1.20-x86_64/utf8# cp ../mumps .
root@060795d9bf65:/opt/yottadb/r1.20-x86_64/utf8# cd
root@060795d9bf65:~# $ydb_dist/mumps -di

YDB>w $ztrnlnm("gtm_dist")
/opt/yottadb/r1.20-x86_64/utf8
YDB>w $ztrnlnm("ydb_dist")
/opt/yottadb/r1.20-x86_64/utf8
YDB>

YDB>h
root@060795d9bf65:~# 
root@060795d9bf65:~# 
root@060795d9bf65:~# exit
```

**Comment by nars1** [comment]
Tomas. Yes. That is on purpose. But I am trying to understand why that is an issue. Can you please explain. Thanks.

**Comment by ztmr** [comment]
OK, so the issue is in the code that tries to simulate UCIs from other MUMPS systems. On GT.M, we had a list of UCIs registered in configuration global and when we have switched in between these, the switch UCI function would take the UCI name and derive the right global directory and routine paths from it -- using environment variables in format of `<UCI>_RTNS` and `<UCI>_GLD`. At the end of each of the routine variables, the `$ZTRNLNM("gtm_dist")` was appended.

So two points:
- this `$ZTRNLNM("gtm_dist")` cannot be used anymore -- we would have to replace it with another name like `gtm_vendor_routines=$gtm_dist` before `gtm_dist` is overriden
- another problem comes related to this (in my context) is that `$zgbldir` cannot be set to `$someEnvVariablePointingToGld` under some circumstances, not sure when exactly yet -- but everything points to JOB'd processes as in direct mode it works fine. That can be fixed too -- instead of setting `$zgbldir="$"_UCI_"_GLD"`, we just do an extra `$ZTRNLNM` on that value

Having these workarounds applied, everything seems to work OK now.

**Comment by nars1** [comment]
Yes we do it just for *_dist variables. Glad you found a workaround.
