### ISSUE TITLE
$ZVERSION is returning the GT.M version rather than the YottaDB Version

### ISSUE THREAD

**Issue by msires** [YottaDB/YottaDB#262]
Example from r122:
MGR> w $ZV
GT.M V6.3-004 Linux x86_64
MGR> w $ZVERSION
GT.M V6.3-004 Linux x86_64

**Comment by ksbhaskar** [comment]
This is as designed. We intend YottaDB to be a drop in replacement for GT.M, and therefore application code that uses $zversion should run unchanged. $zversion also tells you the GT.M version whose source code was merged to create this YottaDB release. Use $zyrelease to query the YottaDB release, e.g., 

```
YDB>write $zyrelease
YottaDB r1.22 Linux x86_64
YDB>write $zversion
GT.M V6.3-004 Linux x86_64
YDB>
```
