### ISSUE TITLE
YottaDB docker container and ^Z

### ISSUE THREAD

**Issue by whitten** [YottaDB/YottaDB#302]
I am running a yottaDB docker container  (created by YottaDB) on a cloud instance

I was working in the command line and must have hit CONTROL-Z

I got this message:

YDB>GTM-MUMPS[33]: %YDB-I-SUSPENDING, Process Received Signal 20. Suspending processing on user request or attempt to do terminal I/O while running in the background -- generated from 0x00007FC6EA74EBC1.

and now I don't know what to type to get the command prompt back.

@whitten 10:51 on 7/5/2018

**Comment by ChristopherEdwards** [comment]
What prompt are you returned to and what command did you use to start the container?

**Comment by ChristopherEdwards** [comment]
Also can you give the output of docker ps -a?

**Comment by whitten** [comment]
There is no return to a prompt. It just sits there.
I typed CNTL-C and CNTL-Z to no avail.

~# docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                    PORTS                                                                                          NAMES
b3540d8dceca        yottadb/yottadb                      "/opt/yottadb/curren…"   12 hours ago        Up 12 hours                                                                                                              fervent_babbage
6b5146561069        yottadb/yottadb                      "/opt/yottadb/curren…"   12 hours ago        Exited (0) 12 hours ago                                                                                                  quirky_wright
e235818f2c2c        yottadb/yottadb                      "/opt/yottadb/curren…"   13 hours ago        Exited (0) 13 hours ago                                                                                                  inspiring_johnson
9235a8783e67        yottadb/yottadb                      "/opt/yottadb/curren…"   13 hours ago        Exited (0) 13 hours ago                                                                                                  thirsty_leakey
8e0d52947a93        yottadb/yottadb                      "/opt/yottadb/curren…"   13 hours ago        Exited (0) 13 hours ago                                                                                                  lucid_curran
043368ef381b        yottadb/yottadb                      "/opt/yottadb/curren…"   13 hours ago        Exited (0) 13 hours ago                                                                                                  upbeat_leavitt
12215536cbbf        yottadb/yottadb                      "/opt/yottadb/curren…"   14 hours ago        Exited (0) 13 hours ago                                                                                                  optimistic_gates
afa0fe7e59cb        yottadb/yottadb                      "/opt/yottadb/curren…"   14 hours ago        Exited (0) 14 hours ago                                                                                                  amazing_carson
9c5dc8ad8ee6        yottadb/yottadb                      "/opt/yottadb/curren…"   14 hours ago        Exited (0) 14 hours ago                                                                                                  nifty_yonath
d65bc6b35600        krmassociates/osehravista-panorama   "/bin/sh -c /home/os…"   5 weeks ago         Up 5 weeks                0.0.0.0:8001->8001/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:9430->9430/tcp, 0.0.0.0:2222->22/tcp   osehravista

**Comment by ChristopherEdwards** [comment]
Try the following: Press and hold Ctrl then press p then q and then release Ctrl. I'm hoping this should return you to your regular shell.

**Comment by whitten** [comment]
This worked. Thank you.

Do I still have a "paused job" out there? 
ie. a container with GT.M paused that I might need to restart and stop ?

Dave

**Comment by ChristopherEdwards** [comment]
@whitten I'd run a ps command in the container and run docker ps -a on the host to confirm that there are no suspended processes. I personally doubt that there are any suspended jobs at this point, but worth checking.

**Comment by ChristopherEdwards** [comment]
@whitten any remaining issue here or can the issue be closed?

**Comment by whitten** [comment]
I have some open questions.  I'm not sure if the ^Z actually paused the
GT.M process or the whole docker container, and if it only paused the GT.M
process, how to restart it.  I don't even know how to find the process id
(which I usually find using the bash command "jobs -p" to see if it is
sitting out there waiting to be restarted.

I expect when I reboot the machine that I will either get a rundown error
if the original process is just paused in the background.

These issues are just to build my knowledge, so I'm okay that this can be
closed.

David

**Comment by ChristopherEdwards** [comment]
David:

It took me a bit to research this. I haven't been able to find a way to bring back the suspended process. It doesn't suspend the whole docker container (just the mumps process). This can be verified by running `docker exec -it {conainerID or nameOfContainer} /bin/bash`. The container will respond and you can see the suspended process (you can also use `docker ps -a` and see that docker is still running the container).

You can issue the `docker stop` and `docker start` commands to ensure the process is killed.
Since the `ydb` script is used to start the container it will perform basic recovery procedures (rundown and journal recover backwards) to ensure a sane environment.

**Comment by nars1** [comment]
@ChristopherEdwards & @whitten : Once you are inside the docker container (using docker exec like mentioned above) doing a "kill -15 <pid>" will restart the suspended process. You will see a REQ2RESUME message in the original terminal where you have the suspended process. Pressing Enter once more will get you back to the YDB> prompt.

**Comment by nars1** [comment]
Update. I had incorrectly mentioned kill -15 in my previous comment. It should instead be "kill -18" (SIGCONT signal, which you can confirm using "kill -l"). I have fixed my previous comment accordingly.

**Comment by nars1** [comment]
I think all remaining issues have been resolved so this issue is now closed.
