### ISSUE TITLE
Compact installation minimizing footprint of engine

### ISSUE THREAD

**Issue by ksbhaskar** [YottaDB/YottaDB#33]
# Final Release Note

The YottaDB install directory size is now 12Mb (noticeably down from 34Mb in prior versions).

# Description

For production deployments in which no development will occur, and where the footprint of the engine matters (e.g., embedded databases in Internet of Things appliances), not all typically installed components are needed. The footprint of a YottaDB as installed should be examined, and options added to the installer (the `configure` script or its replacement) to omit components that are not essential to the core operation of an application. The existing installer has some options already, for example whether to install support for UTF-8, and whether object code files of utility programs should be deleted once a shared library is built. But an application may not even need some or all utility programs in a production deployment (perhaps not even GDE or LKE), and options should be added to omit these.

The above was the original description. Since then, another change happened which noticeably reduced the size of the utility programs (and hence the size of the YottaDB installation). That reduced the size of the installation from 34Mb to 12Mb. And because of that, the above description is considered moot.

# Draft Release Note

The YottaDB install directory size is now 12Mb (noticeably down from 34Mb in prior versions).

**Comment by nars1** [comment]
FYI. I am currently working on reducing the size of the utility programs. That should most likely eliminate the need to make any configure related changes since the new utilities would be very small in size (a few Kbs instead of a few Mbs). It might even change the title and/or the Release Note wording.
