### ISSUE TITLE
%YDB-F-ASSERT, Assert failed in sr_port/gtm_fetch.c line 73 for expression (!TREF(in_zwrite))

### ISSUE THREAD

**Issue by shabiel** [YottaDB/YottaDB#343]
Steps to reproduce:

zwrite a large global
Press CTRL-C
Try to do something else, (like $O)-- you will get the assert.
[YDB_FATAL_ERROR.ZSHOW_DMP_7514_1.txt](https://github.com/YottaDB/YottaDB/files/2291205/YDB_FATAL_ERROR.ZSHOW_DMP_7514_1.txt)

**Comment by nars1** [comment]
@shabiel : This is now fixed at https://gitlab.com/YottaDB/DB/YDB/merge_requests/345. FYI, we have now migrated our repositories to gitlab.
