### ISSUE TITLE
Why isn't --keep-obj the default for ydbinstall?

### ISSUE THREAD

**Issue by seanwoods** [YottaDB/YottaDB#345]
This isn't an issue as much as it's a request for clarification.

After years of using GT.M for personal projects I recently installed YottaDB on a fresh install of Arch Linux.  I love how I can compile it from a virgin system without installing GT.M or YottaDB.

Some of my existing scripts failed because GDE was not available (the scripts set up an environment including create a database file if one does not already exist).

I discovered that the --keep-obj parameter was necessary to copy the GDE.o file to the installed directory for YottaDB.

Why is this?  This seems like a change from the default GT.M installer's behavior which always included GDE.o - wouldn't not including GDE.o cripple your installation if you needed to create a new global directory?

Thanks for any explanation!  Keep up the great work.

**Comment by nars1** [comment]
GDE.o is not installed by default because it is already included in $ydb_dist/libyottadbutil.so. You need to include this file as one element in the search list stored in the ydbroutines/gtmroutines env var. That should get you going even without the --keep-obj.

**Comment by seanwoods** [comment]
Thanks, that makes perfect sense!
